version: "3"

services:
  app:
    image: node:alpine
    container_name: chat_app
    restart: always
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - "5000:5000"
    environment:
      MONGO_INITDB_HOST: chat_mongo
      MONGO_INITDB_DBNAME: chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - mongo
    command: "npm run dev"

  mongo:
    image: mongo
    container_name: chat_mongo
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: chat_dash
    restart: always
    ports:
      - 5001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

volumes:
  mongo:
    external: false
