version: "3"

services:
  app:
    build: .
    container_name:  get_started_express
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - "5000:5000"
    command:
      "npm run dev"
